on:
  schedule:
    # 한국 시간(KST) 기준 매일 06:00 ~ 22:00까지 15분 단위 실행
    # UTC 기준: 매일 21:00 (전날) ~ 13:00 (당일)
    - cron: '0,15,30,45 21,22,23,0,1,2,3,4,5,6,7,8,9,10,11,12 * * *'
  workflow_dispatch: # 수동 실행 버튼 유지
